name: general_utilities
description: A set of general utilites usually needed for any project.
version: 0.0.1
author: Ahmed Ibrahim a.elgammal112@gmail.com
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

