name: general_utilities
description: A set of general utilites that required in any project pure in dart and cut the waste time of repetitive tasks.
version: 0.0.5+1
homepage: https://github.com/nLoops/General-Utilities

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^0.17.4 # SVG pictures.

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

